plugins:
  - jekyll-relative-links
  - jekyll-jupyter-notebook
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
theme: minima
description: Personal web page.
logo: logo.png
title: Nicholas Harley
show_downloads: "true"
